language: node_js
node_js:
  - "12.18.3"
cache: yarn
install:
  - "npm i -f -D"
script:
  - "npx webpack"
deploy:
  provider: s3
  bucket: "devenney.io"
  region: eu-west-1
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master
